# Generated by Django 3.0.3 on 2020-07-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
